update:
	( cd Position/src;              make; cd ../.. )
	( cd ParticleData/src;         make; cd ../.. )
	( cd Orientation/src;           make; cd ../.. )

depend:
	( cd Position/src;      make depend; cd ../.. )
	( cd ParticleData/src; make depend; cd ../.. )	
	( cd Orientation/src;   make depend; cd ../.. )	

clean:
	( cd Position/src;              make clean; cd ../.. )
	( cd ParticleData/src;         make clean; cd ../.. )
	( cd Orientation/src;           make clean; cd ../.. )
	@echo 'Tools deleted'	
