# Basilisk variables
export OCTREE_HOME=${PACIFIC_HOME}/Octree
export BASILISK=${OCTREE_HOME}/basilisk/src
export BASILISK_DLMFD=${OCTREE_HOME}/DLMFD
export PATH="${BASILISK}:${PATH}"
export BASILISK_BITS_DEFAULT=${PACIFIC_BITS_DEFAULT}


# MPI
export BASILISK_MPI_ROOT=${PACIFIC_MPI_ROOT}
export BASILISK_MPI_DISTRIB=${PACIFIC_MPI_DISTRIB}
export BASILISK_MPI_VERSION=${PACIFIC_MPI_VERSION}
export BASILISK_MPI_INCDIR=${PACIFIC_MPI_INCDIR}
export BASILISK_MPI_GFORTRAN_INCDIR=${PACIFIC_MPI_GFORTRAN_INCDIR}
export BASILISK_MPI_BINDIR=${PACIFIC_MPI_BINDIR}
export BASILISK_MPI_LIBDIR=${PACIFIC_MPI_LIBDIR}
export BASILISK_MPI_C=${PACIFIC_MPI_C}


# Serial compiler
export BASILISK_SERCOMPIL_ENV=${PACIFIC_SERCOMPIL_ENV}
export BASILISK_SERCOMPIL_VERSION=${PACIFIC_SERCOMPIL_VERSION}
export BASILISK_C=${PACIFIC_SERCOMPIL_C}
export BASILISK_MESA_GLU_INSTALL=
export LD_LIBRARY_PATH=${BASILISK_MESA_GLU_INSTALL}/lib:${LD_LIBRARY_PATH}
export LD_RUN_PATH=${BASILISK_MESA_GLU_INSTALL}/lib:${LD_RUN_PATH}


# Display
echo -e '\033[95m*** Octree Basilisk shell variables\033[0m'
echo -e '\033[95mOCTREE_HOME\033[0m =' $OCTREE_HOME
echo -e '\033[95mBASILISK\033[0m =' $BASILISK
echo -e '\033[95mBASILISK_BITS_DEFAULT\033[0m =' $BASILISK_BITS_DEFAULT
echo -e '\033[95mBASILISK_SERCOMPIL_ENV\033[0m =' $BASILISK_SERCOMPIL_ENV
echo -e '\033[95mBASILISK_SERCOMPIL_VERSION\033[0m =' $BASILISK_SERCOMPIL_VERSION
echo -e '\033[95mBASILISK_C\033[0m =' $BASILISK_C
echo -e '\033[95mBASILISK_MPI_ROOT\033[0m =' $BASILISK_MPI_ROOT
echo -e '\033[95mBASILISK_MPI_DISTRIB\033[0m =' $BASILISK_MPI_DISTRIB
echo -e '\033[95mBASILISK_MPI_VERSION\033[0m =' $BASILISK_MPI_VERSION
echo -e '\033[95mBASILISK_MPI_INCDIR\033[0m =' $BASILISK_MPI_INCDIR
echo -e '\033[95mBASILISK_MPI_GFORTRAN_INCDIR\033[0m =' $BASILISK_MPI_GFORTRAN_INCDIR
echo -e '\033[95mBASILISK_MPI_BINDIR\033[0m =' $BASILISK_MPI_BINDIR
echo -e '\033[95mBASILISK_MPI_LIBDIR\033[0m =' $BASILISK_MPI_LIBDIR
echo -e '\033[95mBASILISK_MPI_C\033[0m =' $BASILISK_MPI_C
echo -e '\033[95mBASILISK_DLMFD\033[0m =' $BASILISK_DLMFD
echo -e '\033[95mBASILISK_MESA_GLU_INSTALL\033[0m =' $BASILISK_MESA_GLU_INSTALL
