CFLAGS += -DDISPLAY=1
# CFLAGS += -I${BASILISK_MESA_GLU_INSTALL} -L${BASILISK_MESA_GLU_INSTALL}/lib
CFLAGS += -I${OCTREE_HOME}
include ${BASILISK}/Makefile.defs

advect_sphere_mpi.tst: CC=mpicc -D_MPI=4