export HYPRE_DIR=${MACWORLD_ROOT}/hypre-2.10.1
export HYPRE_VERSION=2.10.1
export HYPRE_ARCH=Linux-${MACWORLD_FULL_EXT}
export HYPRE_OPT_FLAGS=${MACWORLD_OPT_FLAGS}
export HYPRE_SHARED_LIB="yes"

echo -e '\033[96mHYPRE_DIR\033[0m =' $HYPRE_DIR
echo -e '\033[96mHYPRE_VERSION\033[0m =' $HYPRE_VERSION
echo -e '\033[96mHYPRE_ARCH\033[0m =' $HYPRE_ARCH
echo -e '\033[96mHYPRE_OPT_FLAGS\033[0m =' $HYPRE_OPT_FLAGS
echo -e '\033[96mHYPRE_SHARED_LIB\033[0m =' $HYPRE_SHARED_LIB

# LD_LIBRARY_PATH
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HYPRE_DIR}/${HYPRE_ARCH}/lib"
