// Gestion de la cinematique pour les objets mobiles
// ============================================================================
#ifndef _Cinematique
#define _Cinematique

/** @brief Gestion de la cinematique pour des objets mobiles.

    Juste pour faire beau dans la doc.

    @author G.FERRER - Institut Francais du Petrole - 2000 - Creation */
// ============================================================================
class Cinematique
{
public:
  /**@name Constructors */
  //@{
  /** @brief Destructeur */
  virtual ~Cinematique() {};
  //@}

protected:
  /**@name Constructors */
  //@{
  /** @brief Constructeur par defaut. */
  Cinematique() {};
  //@}
};

#endif
